Citizen.CreateThread(function()
    AddTextEntry('explorermek', "Ford Explorer")
    AddTextEntry('flatbed3', "Flatbed Mekaniker")
    AddTextEntry('g4svan', "G4S Køretøj")
    AddTextEntry('NEWSVAN', "Nyhedsvogn")
    AddTextEntry('pizzavogn', "Ford Mondeo")
    AddTextEntry('sagkyndig', "Volkswagen Polo")
    AddTextEntry('skraldevogn', "Skraldevogn")
    AddTextEntry('sprinter', "Volkswagen Sprinter")
    AddTextEntry('sagkyndig', "Audi S4 Skolevogn")
    AddTextEntry('cypherct', "Ubermacht Cypher Hatchback")
    AddTextEntry('elegyrh7', "Annis Elegy RH-7")
    AddTextEntry('elegyrh72', "Annis Elegy RH-7H")
    AddTextEntry('elegyx', "Annis Elegy RH8-X")
    AddTextEntry('buffaloh', "Bravado Buffalo Hellhound")
    AddTextEntry('severo', "Pegassi Severo")
    AddTextEntry('oracxsle', "Übermacht Oracle XS-LE")
    AddTextEntry('argento', "Obey Argento")
    AddTextEntry('sultan2c', "Karin Sultan Classic Custom")
    AddTextEntry('gresleyh', "Bravado Gresley Hellhound")
    AddTextEntry('sunrise1', "Maibatsu Sunrise R")
    AddTextEntry('ventoso', "Dinka Ventoso")
    AddTextEntry('stratumc', "Zircoflow Stratum")
    AddTextEntry('scheisser', "Benefactor Scheisser")
    AddTextEntry('italigtr', "Grotti Itali GTR")
    AddTextEntry('paragonxr', "Enus Paragon XR Dragon")
    AddTextEntry('tempestaes', "Pegassi Tempesta Evo Stradale")
    AddTextEntry('sheavas', "Emperor Sheava")
    AddTextEntry('audace', "Lampadati Audace")
end)